### ISSUE TITLE
aqua-registry contribute

### ISSUE THREAD

**Issue by mimikun** [mimikun/maskfiles#2]
## TODO

- [ ] [#catatsuy/purl](#catatsuy/purl)
- [ ] [#mikuta0407/misskey-cli](#mikuta0407/misskey-cli)
- [ ] [#kisielk/errcheck](#kisielk/errcheck)
- [ ] [#fatih/motion](#fatih/motion)
- [ ] [#fatih/gomodifytags](#fatih/gomodifytags)
- [ ] [#nao1215/sqly](#nao1215/sqly)
- [ ] [#klauspost/asmfmt](#klauspost/asmfmt)
- [ ] [#fastfetch-cli/fastfetch](#fastfetch-cli/fastfetch)
- [ ] [#nyaosorg/nyagos](#nyaosorg/nyagos)

いろいろおかしいので今度全部やり直す

---

### klauspost/asmfmt

https://github.com/klauspost/asmfmt

```shell
mask prepare klauspost asmfmt
```

### fastfetch-cli/fastfetch

https://github.com/fastfetch-cli/fastfetch

```shell
mask prepare fastfetch-cli fastfetch
```

### nyaosorg/nyagos

https://github.com/nyaosorg/nyagos

```shell
mask prepare nyaosorg nyagos
```

## go_installの場合

これ参考に作る

```txt
pkgs/google/wire on  base
❯ cat pkg.yaml
packages:
  - name: google/wire@v0.6.0

pkgs/google/wire on  base
❯ cat registry.yaml
packages:
  - type: go_install
    repo_owner: google
    repo_name: wire
    description: Compile-time Dependency Injection for Go
    path: github.com/google/wire/cmd/wire
```

とりあえず以下で実施

### catatsuy/purl

https://github.com/catatsuy/purl

```shell
mask prepare catatsuy purl
```

リリースファイルが入れ子？になっていないのでインストールに失敗する

### mikuta0407/misskey-cli

https://github.com/mikuta0407/misskey-cli

```shell
mask prepare mikuta0407 misskey-cli
```

実行バイナリがそのままリリースに添付されている形式なのでインストールに失敗する

### kisielk/errcheck

https://github.com/kisielk/errcheck

```shell
mask prepare kisielk errcheck
```

バイナリは配布されていないので
`go_install`する必要がある

エラーが出てビルドできない

### fatih/motion

https://github.com/fatih/motion

```shell
mask prepare fatih motion
```

バイナリは配布されていないので
`go_install`する必要がある

エラーが出てビルドできない

### fatih/gomodifytags

https://github.com/fatih/gomodifytags

```shell
mask prepare fatih gomodifytags
```

バイナリは配布されていないので
`go_install`する必要がある

エラーが出てビルドできない

### nao1215/sqly

https://github.com/nao1215/sqly

```shell
mask prepare nao1215 sqly
```

リリースファイルが入れ子？になっていないのでインストールに失敗する

**Comment by mimikun** [comment]
- [ ] https://github.com/twitchdev/twitch-cli
- [ ] https://github.com/mozilla/geckodriver
